
development:
  adapter: postgresql
  encoding: utf8
  database: blog_development
  pool: 5
  username: amitshrestha
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: blog_test
  pool: 5
  username: amitshrestha
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: blog_production
  pool: 5
  username: amitshrestha
  password:
