
development:
  adapter: postgresql
  encoding: unicode
  database: myblog_devel
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: blog_production
  pool: 5
  username:
  password:
